services:
  homeassistant:
    container_name: ha_dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha_config:/config
      - ./custom_components/hiot:/config/custom_components/hiot
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8123:8123"
    restart: unless-stopped
